### ISSUE TITLE
what version of nodejs and npm do you use to building?

### ISSUE THREAD

**Issue by halionsp** [sampotts/plyr#1173]
my OS is archlinux
my version of nodejs: 10.9
my version of npm: 6.4

```
$ npm run build
> plyr@3.4.3 build /home/lauren/Dev/chroot/plyr
> gulp build

/home/lauren/Dev/chroot/plyr/node_modules/git-branch/index.js:6
const readFile = util.promisify(fs.readFile);

TypeError: util.promisify is not a function
    at Object.<anonymous> (/home/lauren/Dev/chroot/plyr/node_modules/git-branch/index.js:6:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lauren/Dev/chroot/plyr/gulpfile.js:18:19)
    at Module._compile (module.js:571:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plyr@3.4.3 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the plyr@3.4.3 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the plyr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs plyr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls plyr
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lauren/.npm/_logs/2018-08-23T22_34_58_356Z-debug.log

```

**Comment by friday** [comment]
This error should not happen in Node v8+
https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original

I'm not getting this in the environment you specified (just switched to Arch days ago). Are you sure you haven't downgraded to an older version via nvm or something similar?

**Comment by halionsp** [comment]
By default the error comes from Arch. It seems that they have not compiled well nodejs. So that's why it failed. I have deleted nodejs from Arch repos and installed the [NVM](https://wiki.archlinux.org/index.php/Node.js_#Installation) instead. Now it's good 😄
