### ISSUE TITLE
Error building plyr

### ISSUE THREAD

**Issue by arankaren** [sampotts/plyr#1485]
### Steps to reproduce

`npm install`
`npm run build`

### Environment

- node v12.5.0
- Operating System: Archlinux
- npm  v6.9.0

### Console errors (if any)

`npm install`

```
38722 silly saveTree │   ├── resolve-from@5.0.0
38722 silly saveTree │   ├── slash@3.0.0
38722 silly saveTree │   ├── specificity@0.4.1
38722 silly saveTree │   ├─┬ string-width@4.1.0
38722 silly saveTree │   │ ├── emoji-regex@8.0.0
38722 silly saveTree │   │ ├── is-fullwidth-code-point@3.0.0
38722 silly saveTree │   │ └─┬ strip-ansi@5.2.0
38722 silly saveTree │   │   └── ansi-regex@4.1.0
38722 silly saveTree │   ├── strip-ansi@5.2.0
38722 silly saveTree │   └── sugarss@2.0.0
38722 silly saveTree ├── stylelint@10.1.0
38722 silly saveTree ├── through2@3.0.1
38722 silly saveTree └── url-polyfill@1.1.5
38723 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
38724 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
38725 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
38725 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
38725 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
38725 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
38726 verbose stack Error: node-sass@4.11.0 postinstall: `node scripts/build.js`
38726 verbose stack Exit status 1
38726 verbose stack     at EventEmitter.<anonymous> (/home/karen/plyr/nodejsenv/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
38726 verbose stack     at EventEmitter.emit (events.js:200:13)
38726 verbose stack     at ChildProcess.<anonymous> (/home/karen/plyr/nodejsenv/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
38726 verbose stack     at ChildProcess.emit (events.js:200:13)
38726 verbose stack     at maybeClose (internal/child_process.js:1021:16)
38726 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
38727 verbose pkgid node-sass@4.11.0
38728 verbose cwd /home/karen/plyr
38729 verbose Linux 4.9.176-gnu-0-lts
38730 verbose argv "/home/karen/plyr/nodejsenv/bin/node" "/home/karen/plyr/nodejsenv/bin/npm" "install"
38731 verbose node v12.5.0
38732 verbose npm  v6.9.0
38733 error code ELIFECYCLE
38734 error errno 1
38735 error node-sass@4.11.0 postinstall: `node scripts/build.js`
38735 error Exit status 1
38736 error Failed at the node-sass@4.11.0 postinstall script.
38736 error This is probably not a problem with npm. There is likely additional logging output above.
38737 verbose exit [ 1, true ]
```

`npm run build`

```
> plyr@3.5.6 build /home/karen/plyr
> gulp build

internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'gulp-sass'
```

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/karen/plyr/nodejsenv/bin/node',
1 verbose cli   '/home/karen/plyr/nodejsenv/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle plyr@3.5.6~prebuild: plyr@3.5.6
6 info lifecycle plyr@3.5.6~build: plyr@3.5.6
7 verbose lifecycle plyr@3.5.6~build: unsafe-perm in lifecycle true
8 verbose lifecycle plyr@3.5.6~build: PATH: /home/karen/plyr/nodejsenv/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/karen/plyr/node_modules/.bin:/home/karen/plyr/nodejsenv/lib/node_modules/.bin:/home/karen/plyr/nodejsenv/bin:/home/karen/plyr/venv/bin:/home/karen/GNUstep/Tools:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/karen/.gem/ruby/2.4.0/bin:/home/karen/.gem/ruby/2.4.0/bin
9 verbose lifecycle plyr@3.5.6~build: CWD: /home/karen/plyr
10 silly lifecycle plyr@3.5.6~build: Args: [ '-c', 'gulp build' ]
11 silly lifecycle plyr@3.5.6~build: Returned: code: 1  signal: null
12 info lifecycle plyr@3.5.6~build: Failed to exec build script
13 verbose stack Error: plyr@3.5.6 build: `gulp build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/karen/plyr/nodejsenv/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/karen/plyr/nodejsenv/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid plyr@3.5.6
15 verbose cwd /home/karen/plyr
16 verbose Linux 4.9.176-gnu-0-lts
17 verbose argv "/home/karen/plyr/nodejsenv/bin/node" "/home/karen/plyr/nodejsenv/bin/npm" "run" "build"
18 verbose node v12.5.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error plyr@3.5.6 build: `gulp build`
22 error Exit status 1
23 error Failed at the plyr@3.5.6 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by arankaren** [comment]
previously required **gulp** and **gulp-sass**

`npm install -g gulp gulp-sass`
