### ISSUE TITLE
vimeo not working

### ISSUE THREAD

**Issue by tiagovignatti** [sampotts/plyr#1515]
It seems that Plyr is not working on vimeo due that funky autoplay browser policy. Console shows the following:

player.js:2 Uncaught (in promise) NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
    at https://player.vimeo.com/api/player.js:2:8705
    at Array.forEach (<anonymous>)
    at b (https://player.vimeo.com/api/player.js:2:8679)
    at e (https://player.vimeo.com/api/player.js:2:10426)

For ease testing:
https://codepen.io/yoyojoma/pen/VopvdX

**Comment by victor-gabou** [comment]
It's a browser policy, you should have the user consent (user interaction) before playing a video. The other way to achieve an autoplay without user consent, is by muting your video.

**Comment by zakickes** [comment]
> It's a browser policy, you should have the user consent (user interaction) before playing a video. The other way to achieve an autoplay without user consent, is by muting your video.

I thought that was the case, but when I try to use the play or pause button on the player, I get the same error. Something funky is happening in Plyr

**Comment by alexanderperrin** [comment]
Unfortunately I'm receiving the same issue. The error appears to occur regardless of user consent (prior interaction). Were you ever able to find a solution for this?
