### ISSUE TITLE
Problem in Building with yarn

### ISSUE THREAD

**Issue by alirezadigi** [sampotts/plyr#2208]
Hi.I am trying to build plyr from source with.I get the latest version source , unzip it and cd to it. Then I perform `sudo yarn install` and then `sudo yarn build`  but I get this error:

``` 
yarn run v1.22.5
$ gulp build
[17:29:00] Loading /home/pi/Desktop/plyr-3.6.7/tasks/build.js
[17:29:06] Loading /home/pi/Desktop/plyr-3.6.7/tasks/deploy.js
Error: .git/HEAD does not exist
    at gitHeadPath (/home/pi/Desktop/plyr-3.6.7/node_modules/git-branch/index.js:36:11)
    at Function.branch.sync (/home/pi/Desktop/plyr-3.6.7/node_modules/git-branch/index.js:25:38)
    at Object.<anonymous> (/home/pi/Desktop/plyr-3.6.7/tasks/deploy.js:56:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.Module._load (/home/pi/Desktop/plyr-3.6.7/node_modules/gulp-hub/lib/load-subfile.js:26:32)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alirezadigi** [comment]
Im in raspbian OS, I also have tried Windows.

**Comment by baligithub** [comment]
Any update in this issue?

**Comment by sampotts** [comment]
Please get the latest from `master` and building should work locally now.
