### ISSUE TITLE
build error (.git/HEAD ERROR)

### ISSUE THREAD

**Issue by coolcjg** [sampotts/plyr#2248]
### Steps to reproduce
yarn install   >>> GOOD
gulp build   >> ERROR

### Environment

- Browser:
- Version:
- Operating System: window   10
- Version:  

### Console errors (if any)

C:\Users\cjg\Downloads\plyr>gulp build
[00:45:28] Loading C:\Users\cjg\Downloads\plyr\tasks\build.js
[00:45:30] Loading C:\Users\cjg\Downloads\plyr\tasks\deploy.js
Error: .git/HEAD does not exist
    at gitHeadPath (C:\Users\cjg\Downloads\plyr\node_modules\git-branch\index.js:36:11)
    at Function.branch.sync (C:\Users\cjg\Downloads\plyr\node_modules\git-branch\index.js:25:38)
    at Object.<anonymous> (C:\Users\cjg\Downloads\plyr\tasks\deploy.js:56:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.Module._load (C:\Users\cjg\Downloads\plyr\node_modules\gulp-hub\lib\load-subfile.js:26:32)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)

I want to build this player.....

**Comment by baligithub** [comment]
Any update in this issue? I am also facing the same.

**Comment by sampotts** [comment]
Please get the latest from `master` and building should work locally now.
