### ISSUE TITLE
Plyr doesn't work on next.js 14

### ISSUE THREAD

**Issue by timomedia** [sampotts/plyr#2770]
I use Plyr on next.js 14 and get the error "document is not defined". Previous versions all worked fine, only when upgrading to next.js 14 did I encounter the above error. Specifically, the error appears as below. Please help me check it
```
⨯ node_modules\plyr\dist\plyr.min.mjs (1:7201) @ document
 ⨯ ReferenceError: document is not defined
    at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
    at eval (./components/player.tsx:11:68)
    at (ssr)/./components/player.tsx (\.next\server\app\[movie]\page.js:249:1)
    at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
    at eval (./app/[movie]/movieDetail.tsx:7:76)
    at (ssr)/./app/[movie]/movieDetail.tsx (\.next\server\app\[movie]\page.js:194:1)
    at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
```
null

**Comment by vvrtsaix** [comment]
Make it client component and use dynamic import

`const Plyr = dynamic(() => import("plyr-react"), { ssr: false });`

**Comment by timomedia** [comment]
> Make it client component and use dynamic import
> 
> `const Plyr = dynamic(() => import("plyr-react"), { ssr: false });`
It really doesn't work. I tried using dynamic but it didn't work. I created a component called Player to use in different pages and using it the way you do doesn't work at all. Below is my original code that tried to use dynamic
```
import React, { useEffect, useRef } from "react";
import dynamic from "next/dynamic";
import Hls from "hls.js";

const PlyrComponent = dynamic(() => import("plyr-react"), { ssr: false });

export default function Player({ videoUrl, poster }) {
    const option = {
        autoplay: false,
        controls: [
            'rewind',
            'play',
            'fast-forward',
            'progress',
            'current-time',
            'duration',
            'mute',
            'volume',
            'settings',
            'quality',
            'fullscreen',
        ],
    };
    const ref = useRef(null);

    useEffect(() => {
        const loadVideo = async () => {
            if (ref.current && typeof window !== 'undefined') {
                const plyr = ref.current.get('plyr');
                if (plyr) {
                    var hls = new Hls();
                    hls.loadSource(videoUrl);
                    hls.attachMedia(plyr.media);

                    hls.on(Hls.Events.MANIFEST_PARSED, function () {
                        plyr.play();
                    });
                }
            }
        };
        loadVideo();
    }, [videoUrl]);
    return (
        <PlyrComponent
            ref={ref}
            playsInline
            source={{
                type: "video",
                sources: [{ src: videoUrl, type: 'application/vnd.apple.mpegurl' }],
            }}
            poster={poster}
            options={option}
        />
    );
}
```

**Comment by oxfist** [comment]
For anyone running into the same issue, the workaround that worked for me in Next.js v13 was changing the import from:

```javascript
import Plyr from 'plyr';
```

to

```javascript
// import dynamic from 'next/dynamic';
const Plyr = dynamic(() => import('plyr-react'), { ssr: false });
```

**Comment by sr-tamim** [comment]
I was also facing this issue in Nextjs 15. I wasn't using Plyr component, rather I am using the Plyr constructor, so above solution didn't work for me.

Below solution worked for my case:
```typescript
const setupPlayer = async () => {
      if (!playerRef.current) return;
      const Plyr = await import('plyr');
      const player = new Plyr.default(playerRef.current, {
           // ... options
      });
}

useEffect(() => {
     setupPlayer();
}, []);
```

**Comment by sampotts** [comment]
I have a basic player on my personal Next 15 site (sampotts.dev). Here's my component:

```tsx
'use client';

/* eslint-disable jsx-a11y/media-has-caption */

import type Plyr from 'plyr';

import type { CSSProperties, VideoHTMLAttributes } from 'react';
import clsx from 'clsx';
import { useEffect, useRef, useState } from 'react';

import 'plyr/dist/plyr.css';

type VideoProps = VideoHTMLAttributes<HTMLVideoElement>;

export function Video(props: VideoProps) {
  const {
    className,
    poster,
    playsInline = true,
    controls = true,
    crossOrigin = 'anonymous',
    ...rest
  } = props;
  const [ref, setRef] = useState<HTMLVideoElement | null>(null);
  const playerRef = useRef<Plyr>(undefined);

  useEffect(() => {
    if (ref && typeof window !== 'undefined') {
      void import('plyr').then(({ default: Plyr }) => {
        playerRef.current = new Plyr(ref, {
          controls: [
            'play-large',
            'play',
            'progress',
            'current-time',
            'mute',
            'fullscreen',
          ],
          previewThumbnails: {
            enabled: true,
            src: [
              'https://cdn.plyr.io/static/demo/thumbs/100p.vtt',
              'https://cdn.plyr.io/static/demo/thumbs/240p.vtt',
            ],
          },
        });
      });
    }
  }, [ref]);

  return (
    <div
      className={clsx(
        'not-prose light:after:border-b-0 relative after:pointer-events-none after:absolute after:inset-0 after:z-10 after:rounded-[inherit] after:border after:border-black/10 dark:after:border-white/10',
        'before:pointer-events-none before:absolute before:inset-px before:z-10 before:rounded-[inherit] before:shadow-light-top before:shadow-white/10 dark:before:hidden',
        className,
      )}
      style={{ '--plyr-color-main': 'var(--color-orange-500)' } as CSSProperties}
    >
      <video
        ref={setRef}
        controls={controls}
        crossOrigin={crossOrigin}
        playsInline={playsInline}
        poster={poster}
        className="rounded-[inherit]"
        {...rest}
      />
    </div>
  );
}
```

**Comment by nillpoe** [comment]
@sampotts I Think I'm in Love with You. **THANK YOUUUUUUUU**
