### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by fmmribeiro** [sampotts/plyr#736]
- [X] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
using gulp should complie the scss

### Actual behaviour
**/Users/franciscoribeiro/Downloads/plyr-master 2/gulpfile.js:93
        );
        ^**
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at execute (/Users/franciscoribeiro/.nvm/versions/node/v6.10.2/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:25:18)
### Environment

- Browser:
- Version:  
- Operating System: MAC
- Version: 

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
- run gulp

**Comment by sampotts** [comment]
Could you check out v3 and see if this is still an issue:
https://github.com/sampotts/plyr/issues/766

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
