### ISSUE TITLE
Ads broken or offline?

### ISSUE THREAD

**Issue by friday** [sampotts/plyr#882]
Currently, on the demo (https://plyr.io/) ads doesn't play, and an error is thrown:

"An unexpected error occurred within the VPAID creative. Refer to the inner error for more info."

This stack trace comes embedded with the error:
```
Error: Error: [object Object]
    at jn (https://imasdk.googleapis.com/js/sdkloader/ima3.js:248:217)
    at pr (https://imasdk.googleapis.com/js/sdkloader/ima3.js:369:35)
    at Y.kb (https://imasdk.googleapis.com/js/sdkloader/ima3.js:362:78)
    at Nd (https://imasdk.googleapis.com/js/sdkloader/ima3.js:54:200)
    at K (https://imasdk.googleapis.com/js/sdkloader/ima3.js:52:290)
    at Ho.A (https://imasdk.googleapis.com/js/sdkloader/ima3.js:270:168)
    at Kd (https://imasdk.googleapis.com/js/sdkloader/ima3.js:50:263)
    at Hd (https://imasdk.googleapis.com/js/sdkloader/ima3.js:51:193)
    at Fd.b (https://imasdk.googleapis.com/js/sdkloader/ima3.js:48:253)
    at i (https://cdn.plyr.io/3.1.0/demo.js:1:18709)
```

Full stack trace:
```
onAdError | @ | ads.js:365
  | (anonymous) | @ | ads.js:236
  | Nd | @ | ima3.js:54
  | K | @ | ima3.js:52
  | pr | @ | ima3.js:369
  | Y.kb | @ | ima3.js:362
  | Nd | @ | ima3.js:54
  | K | @ | ima3.js:52
  | Ho.A | @ | ima3.js:270
  | Kd | @ | ima3.js:50
  | Hd | @ | ima3.js:51
  | Fd.b | @ | ima3.js:48
  | postMessage (async) |   |  
  | VC.sendMessage | @ | bridge3.200.3_en.html:532
  | Vu.send | @ | bridge3.200.3_en.html:350
  | DJ | @ | bridge3.200.3_en.html:739
  | GJ | @ | bridge3.200.3_en.html:739
  | CJ.M | @ | bridge3.200.3_en.html:736
  | ff | @ | bridge3.200.3_en.html:73
  | h.dispatchEvent | @ | bridge3.200.3_en.html:71
  | rt | @ | bridge3.200.3_en.html:325
  | oF | @ | bridge3.200.3_en.html:596
  | nF | @ | bridge3.200.3_en.html:597
  | fF.fa | @ | bridge3.200.3_en.html:595
  | cf | @ | bridge3.200.3_en.html:69
  | Ye | @ | bridge3.200.3_en.html:70
  | We.b | @ | bridge3.200.3_en.html:67
  | postMessage (async) |   |  
  | W | @ | VM2112 AVmanager.js%…073ef448b1087ad6:64
  | h.Y | @ | VM2112 AVmanager.js%…073ef448b1087ad6:61
  | dispatch | @ | VM2131 AVmanager.js:59
  | k.onAdError | @ | VM2131 AVmanager.js:54
  | S | @ | VM2131 AVmanager.js:451
  | a | @ | VM2131 AVmanager.js:431
  | (anonymous) | @ | VM2131 AVmanager.js:439
  | (anonymous) | @ | VM2131 AVmanager.js:304
  | b | @ | VM2131 AVmanager.js:309
  | characterData (async) |   |  
  | e | @ | VM2131 AVmanager.js:309
  | m.exports | @ | VM2131 AVmanager.js:310
  | d | @ | VM2131 AVmanager.js:304
  | c.otherCallFulfilled | @ | VM2131 AVmanager.js:306
  | w.resolve | @ | VM2131 AVmanager.js:306
  | d | @ | VM2131 AVmanager.js:304
  | (anonymous) | @ | VM2131 AVmanager.js:392
  | w.callback | @ | VM2131 AVmanager.js:387
  | (anonymous) | @ | VM2131 AVmanager.js:357
  | a.emit | @ | VM2131 AVmanager.js:395
  | undefined.e.onreadystatechange.e.onreadystatechange | @ | VM2131 AVmanager.js:389
  | XMLHttpRequest.send (async) |   |  
  | w.end | @ | VM2131 AVmanager.js:391
  | w.then | @ | VM2131 AVmanager.js:391
  | (anonymous) | @ | VM2131 AVmanager.js:304
  | (anonymous) | @ | VM2131 AVmanager.js:304
  | u | @ | VM2131 AVmanager.js:305
  | e | @ | VM2131 AVmanager.js:304
  | w.resolve | @ | VM2131 AVmanager.js:306
  | r.resolve | @ | VM2131 AVmanager.js:307
  | b.fetch | @ | VM2131 AVmanager.js:329
  | e.load | @ | VM2131 AVmanager.js:190
  | M | @ | VM2131 AVmanager.js:438
  | d | @ | VM2131 AVmanager.js:449
  | undefined.g.onreadystatechange.g.onreadystatechange | @ | VM2131 AVmanager.js:450
  | XMLHttpRequest.send (async) |   |  
  | e | @ | VM2131 AVmanager.js:450
  | S | @ | VM2131 AVmanager.js:456
  | (anonymous) | @ | VM2131 AVmanager.js:519
  | (anonymous) | @ | VM2131 AVmanager.js:510
  | setTimeout (async) |   |  
  | (anonymous) | @ | VM2131 AVmanager.js:510
  | (anonymous) | @ | VM2131 AVmanager.js:510
  | t.aniviewPlayer | @ | VM2131 AVmanager.js:519
  | w | @ | VM2131 AVmanager.js:54
  | t | @ | VM2131 AVmanager.js:58
  | LinearAd.initAd | @ | VM2131 AVmanager.js:59
  | Z.R | @ | VM2112 AVmanager.js%…073ef448b1087ad6:74
  | Oc | @ | VM2112 AVmanager.js%…073ef448b1087ad6:54
  | Lc | @ | VM2112 AVmanager.js%…073ef448b1087ad6:55
  | Jc.b | @ | VM2112 AVmanager.js%…073ef448b1087ad6:52
  | load (async) |   |  
  | Hc | @ | VM2112 AVmanager.js%…073ef448b1087ad6:51
  | Fc | @ | VM2112 AVmanager.js%…073ef448b1087ad6:51
  | Q.h | @ | VM2112 AVmanager.js%…073ef448b1087ad6:55
  | Z.I | @ | VM2112 AVmanager.js%…073ef448b1087ad6:69
  | Oc | @ | VM2112 AVmanager.js%…073ef448b1087ad6:54
  | Lc | @ | VM2112 AVmanager.js%…073ef448b1087ad6:55
  | Jc.b | @ | VM2112 AVmanager.js%…073ef448b1087ad6:52
  | postMessage (async) |   |  
  | lF | @ | bridge3.200.3_en.html:594
  | mF | @ | bridge3.200.3_en.html:593
  | fF.la | @ | bridge3.200.3_en.html:594
  | cf | @ | bridge3.200.3_en.html:69
  | Ye | @ | bridge3.200.3_en.html:70
  | We.b | @ | bridge3.200.3_en.html:67
  | load (async) |   |  
  | Ue | @ | bridge3.200.3_en.html:66
  | Se | @ | bridge3.200.3_en.html:66
  | Uo | @ | bridge3.200.3_en.html:270
  | P.I | @ | bridge3.200.3_en.html:270
  | h.init | @ | bridge3.200.3_en.html:588
  | CJ.L | @ | bridge3.200.3_en.html:730
  | ff | @ | bridge3.200.3_en.html:73
  | h.dispatchEvent | @ | bridge3.200.3_en.html:71
  | ZC | @ | bridge3.200.3_en.html:534
  | VC.C | @ | bridge3.200.3_en.html:533
  | cf | @ | bridge3.200.3_en.html:69
  | Ye | @ | bridge3.200.3_en.html:70
  | We.b | @ | bridge3.200.3_en.html:67
  | postMessage (async) |   |  
  | Ho.sendMessage | @ | ima3.js:269
  | Fo | @ | ima3.js:269
  | qr | @ | ima3.js:369
  | h.hf | @ | ima3.js:370
  | (anonymous) | @ | ads.js:431
  | Promise.then (async) |   |  
  | play | @ | ads.js:423
  | (anonymous) | @ | listeners.js:299
  | Promise.then (async) |   |  
  | (anonymous) | @ | listeners.js:299
  | playing (async) |   |  
  | play | @ | plyr.js? [sm]:346
  | togglePlay | @ | plyr.js? [sm]:390
  | proxy | @ | listeners.js:423
  | (anonymous) | @ | listeners.js:432
```

Tested with Plyr v3.10 and Chrome and Firefox (doesn't seem like a browser error)

**Comment by sampotts** [comment]
Are you still seeing this? It seems to work ok. We should probably handle the error though...

**Comment by friday** [comment]
Yes, it's still happening to me (force-reloaded with cache and adblockers turned off). It was reported in slack #general by someone else and my response was basically "Are you sure?" until he made me test it.

It doesn't break playback at least.
